### ISSUE TITLE
Calculadora Consola

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-los-3-mosqueteros-topicos#3]
[Reporte calculadora consola y formulario Sugey.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-los-3-mosqueteros-topicos/files/8829026/Reporte.calculadora.consola.y.formulario.Sugey.pdf)
[Calculadoraa.zip](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-los-3-mosqueteros-topicos/files/8824352/Calculadoraa.zip)
[CalculadoraConsola.zip](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-los-3-mosqueteros-topicos/files/8824081/CalculadoraConsola.zip)

**Comment by magaly1311** [comment]
Calificación de Evelyn  18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
